# Generated by Django 4.2.5 on 2023-10-17 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user", models.IntegerField()),
                ("time_stamp", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="GP",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(default="Default Name", max_length=255)),
                ("slots", models.DateField(default=datetime.datetime.now)),
                ("description", models.TextField(default="No description available")),
                (
                    "appointment_ids",
                    models.ManyToManyField(to="consultation_app.appointment"),
                ),
            ],
        ),
    ]
