# Generated by Django 4.2.5 on 2023-10-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("medicine_ids", models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name="Medicines",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
